### ISSUE TITLE
Generated Stream<int> should be Stream<List<int>> for file uploading to work

### ISSUE THREAD

**Issue by pixnbit** [trevorwang/retrofit.dart#140]
Hello, it's me again! One last thing to get the file uploading working:

`final _data = Stream.fromIterable(file.readAsBytesSync());`
should be
`final _data = Stream.fromIterable(file.readAsBytesSync().map((e) => [e]));`

```
flutter: [38;5;196m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────[0m
flutter: [38;5;196m│ #0   _DemoIntroScreenState.build.().() (package:zportal/camera/main.dart:138:28)
flutter: [38;5;196m│ #1   _rootRunUnary (dart:async/zone.dart:1134:38)
flutter: [38;5;196m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄[0m
flutter: [38;5;196m│ ⛔ DioError [DioErrorType.DEFAULT]: 'package:dio/src/dio.dart': Failed assertion: line 992 pos 16: 'data is Stream<List>': Stream type must be `Stream<List>`, but _GeneratedStreamImpl<int> is found.[0m
flutter: [38;5;196m│ ⛔ #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)[0m
flutter: [38;5;196m│ ⛔ #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)[0m
flutter: [38;5;196m│ ⛔ #2      DioMixin._transformData (package:dio/src/dio.dart:992:16)[0m
flutter: [38;5;196m│ ⛔ #3      DioMixin._dispatchRequest (package:dio/src/dio.dart:918:26)[0m
flutter: [38;5;196m│ ⛔ #4      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)[0m
flutter: [38;5;196m│ ⛔ #5      DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1118:22)[0m
flutter: [38;5;196m│ ⛔ #6      DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)[0m
flutter: [38;5;196m│ ⛔ #7      new Future.<anonymous closure> (dart:async/future.dart:176:37)[0m
flutter: [38;5;196m│ ⛔ #8      _rootRun (dart:async/zone.dart:1122:38)[0m
flutter: [38;5;196m│ ⛔ #9      _CustomZone.run (dart:async/zone.dart:1023:19)[0m
flutter: [38;5;196m│ ⛔ #10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)[0m
flutter: [38;5;196m│ ⛔ #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)[0m
flutter: [38;5;196m│ ⛔ #12     _rootRun (dart:async/zone.dart:1126:13)[0m
flutter: [38;5;196m│ ⛔ #13     _CustomZone.run (dart:async/zone.dart:1023:19)[0m
flutter: [38;5;196m│ ⛔ #14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)[0m
flutter: [38;5;196m│ ⛔ #15     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)[0m
flutter: [38;5;196m│ ⛔ #16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)[0m
flutter: [38;5;196m│ ⛔ #17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)[0m
flutter: [38;5;196m│ ⛔ #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)[0m
flutter: [38;5;196m│ ⛔ [0m
flutter: [38;5;196m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────[0m
```

**Comment by trevorwang** [comment]
sorry for missing the type casting.

Please use 1.3.1+2
