### ISSUE TITLE
DioError in flutter_example app

### ISSUE THREAD

**Issue by nikitattt** [trevorwang/retrofit.dart#161]
Hello! Trying to run example application and get `DioError (DioError [DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'List<dynamic>'` error here:
```
final Response<List<dynamic>> _result = await _dio.request('/tags',
        queryParameters: queryParameters,
        options: newOptions.merge(method: 'GET', baseUrl: baseUrl),
        data: _data);
``` 

The downloaded version of Dio: `3.0.9`

**Full error code:**
```
Exception has occurred.
DioError (DioError [DioErrorType.DEFAULT]: type 'String' is not a subtype of type 'List<dynamic>'
#0      DioMixin.assureResponse (package:dio/src/dio.dart:1138:9)
#1      DioMixin._request.<anonymous closure> (package:dio/src/dio.dart:904:14)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#7      Future._complete (dart:async/future_impl.dart:514:7)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:53:12)
#9      Future.any.<anonymous closure> (dart:async/future.dart:459:45)
#10     _rootRunUnary (dart:async/zone.dart:1134:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#18     DioMixin._dispatchRequest (package:dio/src/dio.dart)
<asynchronous suspension>
#19     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:849:37)
#20     DioMixin.checkIfNeedEnqueue (package:dio/src/dio.dart:1117:22)
#21     DioMixin._request._interceptorWrapper.<anonymous closure>.<anonymous closure> (package:dio/src/dio.dart:846:22)
#22     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#23     _rootRun (dart:async/zone.dart:1122:38)
#24     _CustomZone.run (dart:async/zone.dart:1023:19)
#25     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#27     _rootRun (dart:async/zone.dart:1126:13)
#28     _CustomZone.run (dart:async/zone.dart:1023:19)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#30     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#31     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#32     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
)
```

**Comment by trevorwang** [comment]
Please make sure that your server returns a json string `[....]` and the content type is `application/json`

**Comment by nikitattt** [comment]
As I see in your example it should be `json` string and content type is `application/json`.
I even tried adding this to dio instance:
```
final dio = Dio(BaseOptions(
      responseType: ResponseType.json,
      contentType: "application/json"
));
```
So the full code looks like this now:
```
void test() {
  final dio = Dio(BaseOptions(
      responseType: ResponseType.json,
      contentType: "application/json"
  ));
  dio.interceptors.add(InterceptorsWrapper(onRequest: (options) {
    print(options.extra);
    print(options.baseUrl);
    print(options.method);
    print(options.headers);

    return dio.resolve(Response(
        data: jsonEncode([]),
        headers: gg.Headers()
          ..add("content-type", gg.Headers.jsonContentType)));
  }, onResponse: (i) {
    return jsonEncode(["hello", " world"]);
  }));
  final api = RestClient(dio);
  final options = buildCacheOptions(Duration(days: 7));
  dio.options.extra.addAll(options.extra);
  api.getTags().then(print).catchError(print);
}
```
But error still persists.
