### ISSUE TITLE
StaceTrack not enough to understand error/ missing address of error

### ISSUE THREAD

**Issue by tbm98** [trevorwang/retrofit.dart#209]
I have a function is
```
  @POST('time-table')
  Future<List<Schedule>> getLichHoc(
      @Header('token') String token, @Field() String semester);
```
I got error when convert fail
```
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: DioError [DioErrorType.DEFAULT]: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>'
#0      DioMixin.assureResponse (package:dio/src/dio.dart:1138:9)
#1      DioMixin._request.<anonymous closure> (package:dio/src/dio.dart:904:14)
#2      _rootRunUnary (dart:async/zone.dart:1198:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#7      Future._complete (dart:async/future_impl.dart:519:7)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:55:12)
#9      Future.any.onValue (dart:async/future.dart:472:45)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (d<…>
```

but I can't trace my faulty code by above error.

**Comment by trevorwang** [comment]
Did you confirm that the server side returned a List bu not a Map?

**Comment by tbm98** [comment]
@trevorwang no. server side returned a Map, but my code return a List

**Comment by trevorwang** [comment]
Server side gives you Map but you want get a List?  Am I right?

**Comment by tbm98** [comment]
Yes

**Comment by tbm98** [comment]
and then console show log but I can't trace my faulty code by this log

**Comment by trevorwang** [comment]
The framework cannot do this for you. You have to convert this data by yourself.

If you want to get more log details, here's what you need. https://github.com/flutterchina/dio#log

**Comment by tbm98** [comment]
still get more stackTrace but show more about request/response. Thanks
