### ISSUE TITLE
Error: Bad state: No element

### ISSUE THREAD

**Issue by jonasbeyer** [trevorwang/retrofit.dart#278]
**Describe the bug**

It seems that the code generated by a `DELETE` method throws the following exception, but only in the browser:

```
@DELETE("projects/{projectId}")
Future<void> deleteProject(@Path() int projectId);
```

```
Error: Bad state: No element
    at Object.throw_ [as throw] (http://localhost:27325/dart_sdk.js:4328:11)
    at http://localhost:27325/dart_sdk.js:18343:27
    at _RootZone.runGuarded (http://localhost:27325/dart_sdk.js:37356:11)
    at sendDone (http://localhost:27325/dart_sdk.js:31019:24)
    at _SinkTransformerStreamSubscription.new.[_sendDone] (http://localhost:27325/dart_sdk.js:31029:11)
    at _SinkTransformerStreamSubscription.new.[_close] (http://localhost:27325/dart_sdk.js:30941:26)
    at _SinkTransformerStreamSubscription.new.[_close] (http://localhost:27325/dart_sdk.js:35744:22)
    at _EventSinkWrapper.new.close (http://localhost:27325/dart_sdk.js:35684:29)
    at _HandlerEventSink.new.close (http://localhost:27325/dart_sdk.js:35968:16)
    at _SinkTransformerStreamSubscription.new.[_handleDone] (http://localhost:27325/dart_sdk.js:35798:34)
    at _RootZone.runGuarded (http://localhost:27325/dart_sdk.js:37356:11)
    at sendDone (http://localhost:27325/dart_sdk.js:31019:24)
    at _BufferingStreamSubscription.new.[_sendDone] (http://localhost:27325/dart_sdk.js:31029:11)
    at _IterablePendingEvents.new.handleNext (http://localhost:27325/dart_sdk.js:34276:32)
    at async._AsyncCallbackEntry.new.callback (http://localhost:27325/dart_sdk.js:34210:16)
    at Object._microtaskLoop (http://localhost:27325/dart_sdk.js:37708:13)
    at _startMicrotaskLoop (http://localhost:27325/dart_sdk.js:37714:13)
    at http://localhost:27325/dart_sdk.js:33226:9
```

The request is successful if I remove the `data` parameter:

```
  @override
  Future<void> deleteProject(projectId) async {
    ArgumentError.checkNotNull(projectId, 'projectId');
    const _extra = <String, dynamic>{};
    final queryParameters = <String, dynamic>{};
    final _data = <String, dynamic>{};
    await _dio.request<void>('projects/$projectId',
        queryParameters: queryParameters,
        options: RequestOptions(
            method: 'DELETE',
            headers: <String, dynamic>{},
            extra: _extra,
            baseUrl: baseUrl,
        ),
        // data: _data --> has to be removed
   );
    return null;
  }
```

**Comment by rezaei99** [comment]
any progress on this? I have this error too.
