### ISSUE TITLE
Error: Unsupported operation: Platform._pathSeparator

### ISSUE THREAD

**Issue by AnhTu6610** [trevorwang/retrofit.dart#359]
**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**
```
  @POST(API.createProduct)
  Future<HttpResponse<dynamic>> createProduct({
    @Part() required String category,
    @Part() required String name,
    @Part() required String description,
    @Part() required String status,
    @Part(value: "img", contentType: 'application/json') required List<File> img,
  });
==>>

Error: Unsupported operation: Platform._pathSeparator
    at Object.throw_ [as throw] (http://localhost:50940/dart_sdk.js:5041:11)
    at Function._pathSeparator (http://localhost:50940/dart_sdk.js:53430:17)
    at Function.get pathSeparator [as pathSeparator] (http://localhost:50940/dart_sdk.js:53476:27)
    at get _pathSeparator (http://localhost:50940/dart_sdk.js:53389:27)
    at Function.desc.get [as _pathSeparator] (http://localhost:50940/dart_sdk.js:5530:17)
    at Function.get pathSeparator [as pathSeparator] (http://localhost:50940/dart_sdk.js:53339:26)
    at MappedListIterable.new.<anonymous>
    (http://localhost:50940/packages/trival_admin/data_source/network_data/config/restclient.dart.lib.js:77:228)
    at MappedListIterable.new.elementAt (http://localhost:50940/dart_sdk.js:22034:25)
    at ListIterator.new.moveNext (http://localhost:50940/dart_sdk.js:21840:55)
    at JsIterator.next (http://localhost:50940/dart_sdk.js:6709:21)
    at Array.[dartx.addAll] (http://localhost:50940/dart_sdk.js:15369:18)
    at restclient._RestClient.new.createProduct
    (http://localhost:50940/packages/trival_admin/data_source/network_data/config/restclient.dart.lib.js:77:29)
    at createProduct.next (<anonymous>)
    at runBody (http://localhost:50940/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:50940/dart_sdk.js:37453:7)
    at restclient._RestClient.new.createProduct
    (http://localhost:50940/packages/trival_admin/data_source/network_data/config/restclient.dart.lib.js:68:20)
    at create_product_screen._CreateProductScreenState.new.<anonymous>
    (http://localhost:50940/packages/trival_admin/views/create_product_screen.dart.lib.js:1034:37)
    at Generator.next (<anonymous>)
    at runBody (http://localhost:50940/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:50940/dart_sdk.js:37453:7)
    at http://localhost:50940/packages/trival_admin/views/create_product_screen.dart.lib.js:1033:844
    at ink_well._InkResponseState.new.[_handleTap]
    (http://localhost:50940/packages/flutter/src/material/icon_button.dart.lib.js:48455:31)
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:50940/packages/flutter/src/gestures/recognizer.dart.lib.js:183:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:50940/packages/flutter/src/gestures/tap.dart.lib.js:393:40)
    at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:50940/packages/flutter/src/gestures/tap.dart.lib.js:205:12)
    at tap.TapGestureRecognizer.new.acceptGesture (http://localhost:50940/packages/flutter/src/gestures/tap.dart.lib.js:182:23)
    at arena.GestureArenaManager.new.sweep (http://localhost:50940/packages/flutter/src/gestures/arena.dart.lib.js:201:31)
    at binding$5.WidgetsFlutterBinding.new.handleEvent
    (http://localhost:50940/packages/flutter/src/gestures/binding.dart.lib.js:366:27)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent
    (http://localhost:50940/packages/flutter/src/gestures/binding.dart.lib.js:347:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent
    (http://localhost:50940/packages/flutter/src/rendering/layer.dart.lib.js:5022:13)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEventImmediately]
    (http://localhost:50940/packages/flutter/src/gestures/binding.dart.lib.js:321:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent
    (http://localhost:50940/packages/flutter/src/gestures/binding.dart.lib.js:295:43)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue]
    (http://localhost:50940/packages/flutter/src/gestures/binding.dart.lib.js:285:14)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket]
    (http://localhost:50940/packages/flutter/src/gestures/binding.dart.lib.js:276:54)
    at Object.invoke1 (http://localhost:50940/dart_sdk.js:175635:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:50940/dart_sdk.js:157073:15)
    at _engine.PointerBinding.__.[_onPointerData] (http://localhost:50940/dart_sdk.js:157712:49)
    at http://localhost:50940/dart_sdk.js:158130:28
    at http://localhost:50940/dart_sdk.js:158086:16
    at http://localhost:50940/dart_sdk.js:157805:11
```

**Comment by morozevich** [comment]
Is there news about this issue? I have the same situation uploading a image file with multipart.

**Comment by trevorwang** [comment]
Please try  `List<int>` insteadof `File`

**Comment by AnhTu6610** [comment]
I switched to using List<int> and it worked
Thank all
