### ISSUE TITLE
Unhandled Exception: DioError [DioErrorType.DEFAULT]: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>'

### ISSUE THREAD

**Issue by riccardocalligaro** [trevorwang/retrofit.dart#84]
**Describe the bug**

When I try to get this JSON
```json
{
    "lessons": [
        {
            "evtId": 4748798,
            "evtDate": "2019-11-08",
            "evtCode": "LSF0",
            "evtHPos": 1,
            "evtDuration": 1,
            "classDesc": "4IA INFORMATICA",
            "authorName": "xx",
            "subjectId": 215877,
            "subjectCode": "",
            "subjectDesc": "SCIENZE MOTORIE E SPORTIVE",
            "lessonType": "Spiegazione",
            "lessonArg": "Continuazione analisi file sul P.S. fino alle distorsioni"
        },
        {
            "evtId": 4748866,
            "evtDate": "2019-11-08",
            "evtCode": "LSF0",
            "evtHPos": 2,
            "evtDuration": 1,
            "classDesc": "4IA INFORMATICA",
            "authorName": "xx",
            "subjectId": 215877,
            "subjectCode": "",
            "subjectDesc": "SCIENZE MOTORIE E SPORTIVE",
            "lessonType": "Spiegazione",
            "lessonArg": "P.S. simulazioni manovre,"
        }
    ]
}
```
with:
``` 
 @GET("/students/{studentId}/lessons/20191108/20191109")
  Future<List<Lesson>> getTodayLessons(@Path() String studentId);`
```
I get 
```
E/flutter (23023): #28     _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter (23023): #29     _CustomZone.bindCallback.<anonymous closure>  (dart:async/zone.dart:947:23)
E/flutter (23023): #30     Timer._createTimer.<anonymous closure>  (dart:async-patch/timer_patch.dart:21:15)
E/flutter (23023): #31     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (23023): #32     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (23023): #33     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter (23023):
```

This is the lesson class

```dart
import 'package:json_annotation/json_annotation.dart';

part 'lesson.g.dart';

@JsonSerializable()
class Lesson {
  int evtId;
  String evtDate;
  String evtCode;
  int evtHPos;
  int evtDuration;
  String classDesc;
  String authorName;
  int subjectId;
  String subjectCode;
  String subjectDesc;
  String lessonType;
  String lessonArg;

  Lesson(
      {this.evtId,
      this.evtDate,
      this.evtCode,
      this.evtHPos,
      this.evtDuration,
      this.classDesc,
      this.authorName,
      this.subjectId,
      this.subjectCode,
      this.subjectDesc,
      this.lessonType,
      this.lessonArg});

  factory Lesson.fromJson(Map<String, dynamic> json) => _$LessonFromJson(json);
  Map<String, dynamic> toJson() => _$LessonToJson(this);
}

```
Versions:
`
retrofit: ^1.0.1+1
dio: ^3.0.7
`

the only options i set in Dio:
`
dio.options.headers["Content-Type"] = Headers.jsonContentType;
dio.options.headers["User-Agent"] = "xx;
dio.options.headers["Z-Dev-Apikey"] = "xx";

`

Thanks 👍🏻

**Comment by trevorwang** [comment]
Can you provide more detailed log?

**Comment by trevorwang** [comment]
Currently the nested generic is not supported well.  

If you want to the method you defined above, the below data should be returned by your API.

```
 [
        {
            "evtId": 4748798,
            "evtDate": "2019-11-08",
            "evtCode": "LSF0",
            "evtHPos": 1,
            "evtDuration": 1,
            "classDesc": "4IA INFORMATICA",
            "authorName": "xx",
            "subjectId": 215877,
            "subjectCode": "",
            "subjectDesc": "SCIENZE MOTORIE E SPORTIVE",
            "lessonType": "Spiegazione",
            "lessonArg": "Continuazione analisi file sul P.S. fino alle distorsioni"
        },
        {
            "evtId": 4748866,
            "evtDate": "2019-11-08",
            "evtCode": "LSF0",
            "evtHPos": 2,
            "evtDuration": 1,
            "classDesc": "4IA INFORMATICA",
            "authorName": "xx",
            "subjectId": 215877,
            "subjectCode": "",
            "subjectDesc": "SCIENZE MOTORIE E SPORTIVE",
            "lessonType": "Spiegazione",
            "lessonArg": "P.S. simulazioni manovre,"
        }
    ]
```



OR

Create a LessenData class wapper your data

```
 @GET("/students/{studentId}/lessons/20191108/20191109")
  Future<LessenData> getTodayLessons(@Path() String studentId);`
```

**Comment by riccardocalligaro** [comment]
Perfect I will change it. Thank you
